### ISSUE TITLE
Entropy module installation failed

### ISSUE THREAD

**Issue by Sh-Amir** [OMirzaei/AndrODet#1]
Hi Omid, 

I tried to run your python script so as you mentioned in the Readme file, I have to install some packages manually. when I tried to install the entropy module, I got an error saying "Fatal Error": cannot open the input file, exit with status code 1181. 

I tried to search to find a possible solution, but if you already face this error, can you give me a clue how to solve it?

thank you in advance

**Comment by Sh-Amir** [comment]
I solved the problem, by installing the packages from the Entropy repository, but now, I got an error during the script run, which is said syntax error on the code related to the entropy. 

```
\AndrODet-master\AndrODet-master\feature_extraction\EFS.py", line 57, in <module>
   import entropy
 File "c:\users\asharif\downloads\entropy\entropy\__init__.py", line 3, in <module>
   from .entropy import *
 File "c:\users\asharif\downloads\entropy\entropy\entropy.py", line 45
SyntaxError: Non-ASCII character '\xe2' in file c:\users\asharif\downloads\entropy\entropy\entropy.py on line 46, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by Sh-Amir** [comment]
I am able to run it on Mac OSx without any problem, but I have this problem still on the windows.

**Comment by Sh-Amir** [comment]
Sorry for all of this comments, now I managed to run the script but I got 
```
System could not successfully analyze app!
Traceback (most recent call last):
 File "AndrODet_MOA.py", line 217, in detect_obfuscation
   predict_output_IR = IR_module.test(IR_arff_fie)
 File "AndrODet_MOA.py", line 120, in test
   output_file = open(os.path.join(options.output_dir, 'predictions_IR_module'), 'rb')
IOError: [Errno 13] Permission denied: 'C:\\Users\\asharif\\Downloads\\AndrODet-master\\AndrODet-master\\output_dir\\predictions_IR_module'

Traceback (most recent call last):
 File "AndrODet_MOA.py", line 304, in <module>
   os.path.join(options.output_dir, 'features_CF.arff'))
TypeError: 'NoneType' object is not iterable
```
